Project.PL/Controllers/CrsDeptController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Interfaces;
using Project.DAL.Entities;
using Project.PL.ViewModel;

namespace Project.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class CrsDeptController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CrsDeptController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var CrsDepts = _unitOfWork.CrsDeptRepo.GetAll();
            var crsDeptViewModels = _mapper.Map<IEnumerable<CrsDeptViewModel>>(CrsDepts);
            return View(crsDeptViewModels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Courses = _unitOfWork.CourseRepo.GetAll();
            ViewBag.Departments = _unitOfWork.DepartmentRepo.GetAll();
            return View(new CrsDeptViewModel());
        }

        [HttpPost]
        public IActionResult Create(CrsDeptViewModel crsDeptVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var crsDept = _mapper.Map<CourseDepartment>(crsDeptVM);
                    var exist =  _unitOfWork.CrsDeptRepo.GetAll().Any(c=>c.CourseId == crsDeptVM.CourseId && c.DepartmentId==crsDeptVM.DepartmentId);
                    if (!exist)
                    {
                        _unitOfWork.CrsDeptRepo.Add(crsDept);
                        TempData["Message"] = "CourseDepartment Created Successfully!!";
                    }
  
                        return RedirectToAction("Index");
                    
                }
                catch (Exception)
                {
                    throw;
                }
            }
            ViewBag.Courses = _unitOfWork.CourseRepo.GetAll();
            ViewBag.Departments = _unitOfWork.DepartmentRepo.GetAll();
            return View(crsDeptVM);
        }

        public IActionResult Details(int crsId, int deptId)
        {
            var crsDept = _unitOfWork.CrsDeptRepo.GetByIds(crsId, deptId);
            if (crsDept == null)
            {
                return NotFound();
            }

            var crsDeptVM = _mapper.Map<CrsDeptViewModel>(crsDept);

            return View(crsDeptVM);
        }

        //[HttpGet]
        //public IActionResult Update(int crsId, int deptId)
        //{
        //    var crsDept = _unitOfWork.CrsDeptRepo.GetByIds(crsId, deptId);
        //    if (crsDept == null)
        //    {
        //        return NotFound();
        //    }

        //    var crsDeptVM = _mapper.Map<CrsDeptViewModel>(crsDept);
        //    ViewBag.Courses = _unitOfWork.CourseRepo.GetAll();
        //    ViewBag.Departments = _unitOfWork.DepartmentRepo.GetAll();

        //    return View(crsDeptVM);
        //}

        //[HttpPost]
        //public IActionResult Update(CrsDeptViewModel crsDeptVM)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            var crsDept = _mapper.Map<CourseDepartment>(crsDeptVM);
        //            _unitOfWork.CrsDeptRepo.Update(crsDept);
        //            TempData["Message"] = "CourseDepartment Updated Successfully!!";
        //            return RedirectToAction("Index");
        //        }
        //        catch (Exception)
        //        {
        //            throw;
        //        }
        //    }

        //    ViewBag.Courses = _unitOfWork.CourseRepo.GetAll();
        //    ViewBag.Departments = _unitOfWork.DepartmentRepo.GetAll();
        //    return View(crsDeptVM);
        //}

        public IActionResult Delete(int crsId, int deptId)
        {
            var crsDept = _unitOfWork.CrsDeptRepo.GetByIds(crsId, deptId);
            if (crsDept == null)
            {
                return NotFound();
            }

            var crsDeptVM = _mapper.Map<CrsDeptViewModel>(crsDept);
            _unitOfWork.CrsDeptRepo.Delete(crsDept);
            return RedirectToAction("Index");
        }

    }
}

Project.PL/Views/CrsDept/Create.cshtml
@{
    ViewData["Title"] = "Add Course Department";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Add Course Department</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Add Course Department</h3>
                </div>
                <form asp-action="Create" asp-controller="CrsDept" enctype="multipart/form-data">

                    <partial name="PartialViews/CreateUpdatePartialView" />

                    <div class="mt-5 mx-3 mb-3">
                        <input type="submit" value="Add" class="btn btn-primary" />
                        <a class="btn btn-dark" asp-action="Index">Back To List</a>
                    </div>
                </form>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div>
</div>

Project.PL/Views/CrsDept/Details.cshtml
@model CrsDeptViewModel
@{
    ViewData["Title"] = "Course Department Details";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
    // var Courses = new SelectList(ViewBag.Courses, "CourseId", "CrsName");
    // var Departments = new SelectList(ViewBag.Departments, "DepartmentId", "DeptName");
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success">
        <h3>@TempData["Message"]</h3>
    </div>
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Course Department Details</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Course Department Details</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="@Model.DepartmentId" class="col-form-label"></label>
                                    <input asp-for="@Model.DepartmentId" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="@Model.CourseId" class="col-form-label"></label>
                                    <input asp-for="@Model.CourseId" class="form-control" readonly />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
                        <div class="text-center mt-5 mb-3">
                            @* <a asp-action="Update" asp-route-id="@Model.DepartmentId" asp-route-id="@Model.CourseId" class="btn btn-sm btn-primary">Edit Department</a> *@
                            <a asp-action="Delete" asp-route-id="@Model.DepartmentId" asp-route-id="@Model.CourseId" class="btn btn-sm btn-warning">Delete Department</a>
                            <a class="btn btn-light" asp-action="Index">Back To List</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
    </div>
    <!-- /.card -->
    </section>
    <!-- /.content -->
</div>

Project.PL/Views/CrsDept/Index.cshtml
@model IEnumerable<CrsDeptViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) ------>
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Course Department</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <form class="my-3" asp-action="Index" asp-controller="CrsDept">
            <div class="row">
                <div class="col-sm-8">
                    <input placeholder="Search By Department Id" name="SearchValue" class="form-control" />
                </div>
                <div class="col-sm-4">
                    <input type="submit" value="Search" class="btn btn-success btn-block" />
                </div>
            </div>
        </form>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Course Department</h3>
                </div>
                <div class="card-body p-0">
                    @if (Model?.Count() > 0)
                    {
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.CourseId)
                                    </th>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.DepartmentId)
                                    </th>
                                    <th style="width: 20%">
                                    </th>
                                    <th style="width: 1%" class="text-center">
                                    </th>
                                    <th style="width: 30%">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.CourseId
                                        </td>
                                        <td>
                                            @item.DepartmentId
                                        </td>
                                        <td class="project_progress">
                                        </td>
                                        <td class="project-state">
                                        </td>
                                        <td class="project-actions text-right">
                                            <a class="btn btn-primary btn-sm"
                                               asp-action="Details"
                                               asp-route-crsId="@item.CourseId"
                                               asp-route-deptId="@item.DepartmentId">
                                                <i class="fas fa-folder"></i>
                                                View
                                            </a>
@*                                             <a class="btn btn-info btn-sm"
                                               asp-action="Update"
                                               asp-route-crsId="@item.CourseId"
                                               asp-route-deptId="@item.DepartmentId">
                                                <i class="fas fa-pencil-alt"></i>
                                                Edit
                                            </a> *@

                                            <a class="btn btn-danger btn-sm"
                                               asp-action="Delete"
                                               asp-route-crsId="@item.CourseId"
                                               asp-route-deptId="@item.DepartmentId">
                                                <i class="fas fa-trash"></i>
                                                Delete
                                            </a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-warning">
                            <h4>No Course Department Found!!</h4>
                        </div>
                    }
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <div class="row">
            <div class="col-12">
                <a asp-action="Create" class="btn btn-success float-right">Create new Course Department</a>
            </div>
        </div>
        <!-- /.content -->
    </div>
</div>

Project.PL/Views/CrsDept/Update.cshtml
@{
    ViewData["Title"] = "Edit Course Department";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Edit Course Department</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Course Department</h3>
                </div>
                <form asp-action="Update" asp-controller="CrsDept" enctype="multipart/form-data">

                    <partial name="PartialViews/CreateUpdatePartialView" />

                    <div class="mt-5 mx-3 mb-3">
                        <input type="submit" value="Update" class="btn btn-primary" />
                        <a class="btn btn-dark" asp-action="Index">Back To List</a>
                    </div>
                </form>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div>
</div>