Project.PL/Controllers/CrsInstController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Interfaces;
using Project.DAL.Entities;
using Project.PL.ViewModel;

namespace Project.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class CrsInstController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        public CrsInstController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var CrsInsts = _unitOfWork.CrsInstRepo.GetAll();
            var CrsInstViewModels = _mapper.Map<IEnumerable<CrsInstViewModel>>(CrsInsts);
            return View(CrsInstViewModels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Courses = _unitOfWork.CourseRepo.GetAll();
            ViewBag.Instructors = _unitOfWork.InstructorRepo.GetAll();
            return View(new CrsInstViewModel());
        }

        [HttpPost]
        public IActionResult Create(CrsInstViewModel CrsInstVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var CrsInst = _mapper.Map<CourseInstructor>(CrsInstVM);
                    var exist = _unitOfWork.CrsInstRepo.GetAll().Any(c => c.CourseId == CrsInstVM.CourseId && c.InstructorId == CrsInstVM.InstructorId);
                    if(!exist)
                    {
                        _unitOfWork.CrsInstRepo.Add(CrsInst);
                        TempData["Message"] = "CrsInst Created Successfully!!";
                    }

                       return RedirectToAction("Index"); 
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
            ViewBag.Courses = _unitOfWork.CourseRepo.GetAll();
            ViewBag.Instructors = _unitOfWork.InstructorRepo.GetAll();
            return View(CrsInstVM);
        }

        public IActionResult Delete(int crsId, int InsId)
        {
            var crsIns = _unitOfWork.CrsInstRepo.GetByIds(crsId, InsId);
            if (crsIns == null)
            {
                return NotFound();
            }

            var crsInsVM = _mapper.Map<CrsInstViewModel>(crsIns);
            _unitOfWork.CrsInstRepo.Delete(crsIns);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int crsId, int InsId)
        {
            var crsIns = _unitOfWork.CrsInstRepo.GetByIds(crsId, InsId);
            if (crsIns == null)
            {
                return NotFound();
            }

            var crsInsVM = _mapper.Map<CrsInstViewModel>(crsIns);

            return View(crsInsVM);
        }
    }
}

Project.PL/Views/CrsInst/Create.cshtml
@{
    ViewData["Title"] = "Add Course Instructor";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active"> Add Course Instructor</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Add Course Instructor</h3>
                </div>
                <form asp-action="Create" asp-controller="CrsInst" enctype="multipart/form-data">

                    <partial name="PartialViews/CreateUpdatePartialView" />

                    <div class="mt-5 mx-3 mb-3">
                        <input type="submit" value="Add" class="btn btn-primary" />
                        <a class="btn btn-dark" asp-action="Index">Back To List</a>
                    </div>
                </form>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div>
</div>

Project.PL/Views/CrsInst/Details.cshtml
@model CrsInstViewModel
@{
    ViewData["Title"] = "Course Department Details";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
    
}



<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Course Instructor Details</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Course Instructor Details</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="@Model.InstructorId" class="col-form-label"></label>
                                    <input asp-for="@Model.InstructorId" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="@Model.CourseId" class="col-form-label"></label>
                                    <input asp-for="@Model.CourseId" class="form-control" readonly />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
                        <div class="text-center mt-5 mb-3">
                           
                            <a asp-action="Delete" asp-route-InsId="@Model.InstructorId" asp-route-crsId="@Model.CourseId" class="btn btn-sm btn-warning">Delete course</a>
                            <a class="btn btn-light" asp-action="Index">Back To List</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
    </div>
    <!-- /.card -->
    </section>
    <!-- /.content -->
</div>

Project.PL/Views/CrsInst/Index.cshtml
@model IEnumerable<CrsInstViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) ------>
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Course Instructor</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <form class="my-3" asp-action="Index" asp-controller="CrsInst">
            <div class="row">
                <div class="col-sm-8">
                    <input placeholder="Search By Instructor Id" name="SearchValue" class="form-control" />
                </div>
                <div class="col-sm-4">
                    <input type="submit" value="Search" class="btn btn-success btn-block" />
                </div>
            </div>
        </form>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Course Instructor</h3>
                </div>
                <div class="card-body p-0">
                    @if (Model?.Count() > 0)
                    {
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.CourseId)
                                    </th>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.InstructorId)
                                    </th>
                                    <th style="width: 20%">
                                    </th>
                                    <th style="width: 1%" class="text-center">
                                    </th>
                                    <th style="width: 30%">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.CourseId
                                        </td>
                                        <td>
                                            @item.InstructorId
                                        </td>
                                        <td class="project_progress">
                                        </td>
                                        <td class="project-state">
                                        </td>
                                        <td class="project-actions text-right">
                                            <a class="btn btn-primary btn-sm"
                                               asp-action="Details"
                                               asp-route-InsId="@item.InstructorId" asp-route-crsId="@item.CourseId">
                                                <i class="fas fa-folder"></i>
                                                View
                                            </a>

                                            <a class="btn btn-danger btn-sm"
                                               asp-action="Delete"
                                               asp-route-InsId="@item.InstructorId" asp-route-crsId="@item.CourseId">
                                                <i class="fas fa-trash"></i>
                                                Delete
                                            </a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-warning">
                            <h4>No Course Instructor Found!!</h4>
                        </div>
                    }
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <div class="row">
            <div class="col-12">
                <a asp-action="Create" class="btn btn-success float-right">Create new Course Instructor</a>
            </div>
        </div>
        <!-- /.content -->
    </div>
</div>