Project.PL/Controllers/QuestionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Interfaces;
using Project.DAL.Entities;
using Project.PL.ViewModel;
using System.Collections.Generic;
using System.Security.Claims;

namespace Project.PL.Controllers
{
    [Authorize(Roles = "Instructor")]

    public class QuestionController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public QuestionController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }


        public IActionResult Index()
        {
            var allQuestions = _unitOfWork.QuestionRepo.getAllQuestionsWithCourses(); 
            List<Question> questionList = new List<Question>(); 
            var courses = getInstructorCourses();
            if (courses != null)
            {
                foreach(var course in courses)
                {
                   var questions =  allQuestions.Where(q => q.CourseId == course.CourseId);
                    if (questions != null)
                    {
                        foreach(var question in questions)
                        {
                            questionList.Add(question);
                        }
                    }
                }
            }
            
            return View(questionList);
        }

   

        public IActionResult AddQuestion()
        {
             //ViewBag.allcourses = _unitOfWork.CourseRepo.GetAll().ToList();
             ViewBag.Courses = getInstructorCourses();
             return View();
        }


        private List<Course> getInstructorCourses()
        {
            string name = User.Identity.Name;

            string id = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;

            var instructor = _unitOfWork.InstructorRepo.getInstructorByUserId(id);

            var insCourses = _unitOfWork.CourseRepo.getCoursesByInsId(instructor.InstructorId);

            return insCourses;

        }


        [HttpPost]
        public IActionResult AddQuestion(IFormCollection f)
        {

            ViewBag.allcourses = _unitOfWork.CourseRepo.GetAll().ToList();
            Choice first = new() { ChoiceTxt = f["firstChoice"]  , IsCorrect=0 };
            Choice second = new() { ChoiceTxt = f["secondChoice"], IsCorrect = 0 };
            Choice third = new() { ChoiceTxt = f["thirdChoice"], IsCorrect = 0 };
            Choice forth = new() { ChoiceTxt = f["forthChoice"], IsCorrect = 0 };
            Choice[] choices = [first, second, third, forth];


            _unitOfWork.ChoiceRepo.Add(first);
            _unitOfWork.ChoiceRepo.Add(second);
            _unitOfWork.ChoiceRepo.Add(third);
            _unitOfWork.ChoiceRepo.Add(forth);
            int c = int.Parse(f["ModelAnswer"]);
            var ch = choices[c].ChoiceTxt;
            choices[c].IsCorrect = 1; 
            Question newQuest = new() { Choices = choices.ToList(), QuestionText = f["qBody"], QuestionType = "MCQ", QuestionAnswer = ch , CourseId = int.Parse(f["CourseId"]) };

            _unitOfWork.QuestionRepo.Add(newQuest);

            foreach(var choice in choices)
            {
                choice.QuestionId = newQuest.QuestionId;
                _unitOfWork.ChoiceRepo.Update(choice);
            }

            return RedirectToAction("AddQuestion" );

        }



        public IActionResult AddTFQuestion()
        {
            ViewBag.allcourses = getInstructorCourses();
            return View();  
        }


        [HttpPost]
        public IActionResult AddTFQuestion(IFormCollection f)
        {
            ViewBag.allcourses = _unitOfWork.CourseRepo.GetAll().ToList();
            Choice first = null;
            Choice second = null;


           /* if (_unitOfWork.ChoiceRepo.getChoicesValue("True") > 0)
            {
                first = _unitOfWork.ChoiceRepo.getChoiceByValue("True");
            }
            else
            {
              // _unitOfWork.ChoiceRepo.Add(first);
           }
            if (_unitOfWork.ChoiceRepo.getChoicesValue("False") > 0)
            {
               // second = _unitOfWork.ChoiceRepo.getChoiceByValue("False");
            }
            else
            {
               // _unitOfWork.ChoiceRepo.Add(second);
           // } */

            first = new() { ChoiceTxt = "True" };
            second = new() { ChoiceTxt = "False" };
            Choice[] choices = [first, second];

            int c = int.Parse(f["ModelAnswer"]);
            var ch = choices[c].ChoiceTxt;
            Question newQuest = new() { Choices = null, QuestionText = f["qBody"], QuestionType = "TF", QuestionAnswer = ch , CourseId = int.Parse(f["CourseId"] ) };

            _unitOfWork.QuestionRepo.Add(newQuest);

          /*  foreach (var choice in choices)
            {
                choice.QuestionId = newQuest.QuestionId;
                _unitOfWork.ChoiceRepo.Update(choice);
            }*/

            return RedirectToAction("AddTFQuestion");
        }


        [HttpPost]
        public IActionResult UpdateTFQuestion(IFormCollection f)
        {
            ViewBag.allcourses = _unitOfWork.CourseRepo.GetAll().ToList();

            int c = int.Parse(f["ModelAnswer"]);
            var ch = c==0?"True":"False";
            Question newQuest = new() { Choices = null, QuestionText = f["qBody"], QuestionType = "TF", QuestionAnswer = ch, CourseId = int.Parse(f["CourseId"]) };

            _unitOfWork.QuestionRepo.Update(newQuest);


            return RedirectToAction("Index");
        }


        public IActionResult UpdateTFQuestion(int? id )
        {
            if (id is null)
                return NotFound();
            var question = _unitOfWork.QuestionRepo.GetById(id);
            if (question is null)
                return NotFound();

            ViewBag.allcourses = getInstructorCourses();


            return View(question);
        }



        public IActionResult UpdateMCQQuestion(int? id)
        {
            if (id is null)
                return NotFound();

            var question = _unitOfWork.QuestionRepo.GetById(id);

            if (question is null)
                return NotFound();

            var questionVM = _mapper.Map<QuestionViewModel>(question);
            ViewBag.Courses = getInstructorCourses();
            ViewBag.Choices = _unitOfWork.ChoiceRepo.GetAll().Where(ch => ch.QuestionId == id).ToList();

            return View(questionVM);
        }


        [HttpPost]
        public IActionResult UpdateMCQQuestion(int id , IFormCollection f)
        {


            if (ModelState.IsValid)
            {
                try
                {
                   var choices =  _unitOfWork.ChoiceRepo.GetAll().Where(ch => ch.QuestionId == id).ToList();
                    choices[0].ChoiceTxt = f["firstChoice"];
                    choices[1].ChoiceTxt = f["secondChoice"];
                    choices[2].ChoiceTxt = f["thirdChoice"];
                    choices[3].ChoiceTxt = f["forthChoice"];
                    foreach(var item in choices)
                    {     
                        _unitOfWork.ChoiceRepo.Update(item);
                    }
                    var question = _unitOfWork.QuestionRepo.GetById(id);
                    question.QuestionText = f["qBody"]; 
                    question.QuestionAnswer = choices[int.Parse(f["ModelAnswer"])].ChoiceTxt;
                    question.CourseId = int.Parse(f["CourseId"]) ; 
                    _unitOfWork.QuestionRepo.Update(question);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
            
            return View();
        }



        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            if (id is null)
                return NotFound();

            var question = _unitOfWork.QuestionRepo.GetById(id);

            if (question is null)
                return NotFound();

            _unitOfWork.ChoiceRepo.deleteQuestionChoices(question.QuestionId);
            _unitOfWork.ExamQuestionRepo.deleteQuestionFromExam(question.QuestionId);
            _unitOfWork.StudentExamQuestionRepo.deleteStudentAnswerOnQues(question.QuestionId);
            _unitOfWork.QuestionRepo.Delete(question);
            return RedirectToAction(nameof(Index));
        }



    }
}

Project.PL/Views/Question/AddQuestion.cshtml
@{
    ViewData["Title"] = "AddQuestion";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<h1>AddQuestion</h1>


<!--app-content open-->
<div class="main-content app-content mt-0">
    <div class="side-app">

        <!-- CONTAINER -->
        <div class="main-container container-fluid">

            <!-- PAGE-HEADER -->
            <div class="page-header">

            </div>
            <div class="card">

                <div class="card-body">
                    <div class="card-pay">
                        <ul class="tabs-menu nav">
                            <li class="" style="width: 50%;"><a href="#tab20" class="active" data-bs-toggle="tab">Multiple Choices</a></li>
                            <!-- <li style="width: 50%;"><a href="#tab21" data-bs-toggle="tab" class="">  True & False</a></li>-->
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active show" id="tab20">
                                <form method="post">
                                    <div class="form-group">
                                        <label class="form-label">Question Body: </label>
                                        <input type="text" name="qBody" class="form-control" placeholder="   ">
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6 col-md-6">
                                            <div class="form-group ">
                                                <label class="form-label">Choice 1:</label>
                                                <input type="text" name="firstChoice" class="form-control" required="">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <label class="form-label">Choice 2:</label>
                                                <input type="text" name="secondChoice" class="form-control" required="">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6">
                                            <div class="form-group ">
                                                <label class="form-label">Choice 3:</label>
                                                <input type="text" name="thirdChoice" class="form-control" required="">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6">
                                            <div class="form-group ">
                                                <label class="form-label">Choice 4:</label>
                                                <input type="text" name="forthChoice" class="form-control" required="">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6">
                                            <div class="form-group ">
                                                <label class="form-label">Model Answer: </label>
                                                <select name="ModelAnswer" class="form-control form-select select2 " data-bs-placeholder="Select Correct Choice">

                                                    <option value="0">1</option>
                                                    <option value="1">2</option>
                                                    <option value="2">3</option>
                                                    <option value="3">4</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Course Name: </label>
                                        <select name="CourseId" class="form-control form-select select2 " data-bs-placeholder="Select Course">
                                            @foreach (Course c in ViewBag.allcourses)
                                            {
                                                <option value="@c.CourseId">@c.CrsName</option>
                                            }
                                        </select>
                                    </div>
                              
                                    <input type="submit" class="btn  btn-lg btn-primary" value="Confirm" style="margin: auto;">
                                </form>
                            </div>




                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

Project.PL/Views/Question/AddTFQuestion.cshtml
@{
    ViewData["Title"] = "AddTFQuestion";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<h1>AddTFQuestion</h1>


<div class="tab-pane" id="tab21">
    <form method="post" action="/Question/AddTFQuestion">   
        <div class="form-group">
            <label class="form-label">Question Body: </label>
            <input type="text" name="qBody" class="form-control" placeholder="   ">
        </div>
        <div class="row">

            <div class="form-group">
                <label class="form-label">Model Answer: </label>
                <select name="ModelAnswer" class="form-control form-select select2 " data-bs-placeholder="Select Country">
                    <option value="0">True</option>
                    <option value="1">False</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="form-label">Course Name: </label>
            <select name="CourseId" class="form-control form-select select2 " data-bs-placeholder="Select Country">
                @foreach (Course c in ViewBag.allcourses)
                {
                    <option value="@c.CourseId">@c.CrsName</option>
                }
            </select>
        </div>
        <div class="mt-5 mx-3 mb-3">
            <input type="submit" value="Add" class="btn btn-primary" />
            <a class="btn btn-dark" asp-action="Index">Back To List</a>
        </div>
@*         <input type="submit" class="btn  btn-lg btn-primary" value="Confirm" style="margin: auto;">
 *@    </form>
</div>

Project.PL/Views/Question/Index.cshtml
@model IEnumerable<Question>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}

<div id="content" class="p-4 p-md-5 pt-5">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#" class="text-secondary">Home</a></li>
                            <li class="breadcrumb-item active">Questions</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content mb-3">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Questions</h3>
                </div>
                <div class="card-body p-0">
                    @if (Model?.Count() > 0 && Model !=null)
                    {
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.QuestionId)
                                    </th>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.QuestionText)
                                    </th>
                                    <th style="width: 20%">
                                        @Html.DisplayNameFor(M => M.QuestionAnswer)
                                    </th>
                                    <th style="width: 30%">
                                        @Html.DisplayNameFor(M => M.QuestionType)
                                    </th>
                                    <th style="width: 30%">
                                        @Html.DisplayNameFor(M => M.CourseId)
                                    </th>
                                    <th>

                                    </th>
                                    <th style="width: 8%" class="text-center">
                                    </th>
                                    <th style="width: 28%">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.QuestionId
                                        </td>
                                        <td>
                                            @item.QuestionText
                                        </td>
                                        <td>
                                            @item.QuestionAnswer
                                        </td>
                                        <td>
                                            @item.QuestionType
                                        </td>
                                        <td>
                                            @item.Course.CrsName
                                        </td>
                                        <td class="project_progress">
                                        </td>
                                        <td class="project-state">
                                        </td>
                                         <td class="project-actions text-right">
                                            @if (item.QuestionType == "TF")
                                            {
                                                <a class="btn btn-info btn-sm text-white" asp-action="UpdateTFQuestion" asp-route-id="@item.QuestionId">
                                                    <i class="fas fa-pencil-alt text-white">
                                                    </i>
                                                    Edit
                                                </a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-info btn-sm text-white" asp-action="UpdateMCQQuestion" asp-route-id="@item.QuestionId">
                                                <i class="fas fa-pencil-alt text-white">
                                                </i>
                                                Edit
                                                </a>    
                                                
                                            }
                                            <a class="btn btn-danger btn-sm" onclick="deleteQues(@item.QuestionId)">
                                        <i class="fas fa-trash text-white">
                                        </i>
                                        Delete
                                        </a>
                                        </td> 
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-warning">
                            <h4>No Questions Found!!</h4>
                        </div>
                    }
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <div class="row">
            <div class="col-12">
                <a asp-action="AddQuestion" class="btn btn-success float-right">Create new Question</a>
            </div>
        </div>
        <!-- /.content -->
    </div>
</div>



@section Scripts{


    <script>

        function deleteQues(id) {
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
               if (result.value) {
                $.ajax({
                    url: `/Question/Delete/${id}`,
                    type: 'DELETE',
                    success: function (data) {
                        /*Swal.fire({
                            title: "Deleted!",
                            text: "Your file has been deleted.",
                            icon: "success"
                        });*/
                        location.reload(); 
                    },
                    error: function (err) {

                    },
                })
                }
            });

        }

    </script>

}



            

Project.PL/Views/Question/UpdateMCQQuestion.cshtml
@{
    ViewData["Title"] = "UpdateMCQQuestion";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
}



<div class="main-content app-content mt-0">
    <div class="side-app">

        <!-- CONTAINER -->
        <div class="main-container container-fluid">

            <!-- PAGE-HEADER -->
            <div class="page-header">
            </div>
            <div class="card">

                <div class="card-body">
                    <div class="card-pay">
                        <ul class="tabs-menu nav">
                            <li class="" style="width: 50%;"><a href="#tab20" class="active" data-bs-toggle="tab">Update MCQ Question </a></li>
                            <!-- <li style="width: 50%;"><a href="#tab21" data-bs-toggle="tab" class="">  True & False</a></li>-->
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active show" id="tab20">
                                <form method="post" asp-action="UpdateMCQQuestion" asp-controller="Question">
                                    <partial name="PartialViews/CreateUpdatePartialView" />

                                    <input type="submit" class="btn  btn-lg btn-primary" value="Confirm" style="margin: auto;">
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

Project.PL/Views/Question/UpdateTFQuestion.cshtml
@model Question

@{
    ViewData["Title"] = "UpdateTFQuestion";
    Layout = "~/Views/Shared/_AdminBoardLayout.cshtml";
    SelectList courses = new SelectList(ViewBag.allcourses, "CourseId", "CrsName" , Model.CourseId);
    var items = new List<SelectListItem>
    {
    new SelectListItem { Value = "0", Text = "True" },
    new SelectListItem { Value = "1", Text = "False" },
    };
    SelectList choices = new SelectList(items, "Value", "Text" , Model.QuestionAnswer=="True"?"0":"1");
   
}

<h1>UpdateTFQuestion</h1>

<div class="tab-pane" id="tab21">
    <form asp-action="UpdateTFQuestion" asp-controller="Question">
        <div class="form-group">
            <label class="form-label">Question Body: </label>
            <input type="text" name="qBody" class="form-control" value="@Model.QuestionText">
        </div>
        <div class="row">

            <div class="form-group">
                <label class="form-label">Model Answer: </label>
                <select name="ModelAnswer" class="form-control form-select select2" asp-items="choices" >
                   @*  <option value="0">True</option>
                    <option value="1">False</option> *@
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="form-label">Course Name: </label>
            <select name="CourseId" class="form-control form-select select2 " asp-items="courses" asp-for="CourseId">
              @*   @foreach (Course c in ViewBag.allcourses)
                {
                    <option value="@c.CourseId">@c.CrsName</option>
                } *@
            </select>
        </div>
        <div class="mt-5 mx-3 mb-3">
            <input type="submit" value="Update" class="btn btn-primary" />
            <a class="btn btn-dark" asp-action="Index">Back To List</a>
        </div>
        @*         <input type="submit" class="btn  btn-lg btn-primary" value="Confirm" style="margin: auto;">
        *@
    </form>
</div>

Project.PL/Views/Question/create.cshtml
@model Project.PL.ViewModel.QuestionViewModel

<h2>Create Question</h2>

@using (Html.BeginForm("Create", "Question", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(model => model.QuestionId, htmlAttributes: new { @class = "control-label" })
        @Html.TextBoxFor(model => model.QuestionId, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.QuestionId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QuestionText, htmlAttributes: new { @class = "control-label" })
        @Html.TextBoxFor(model => model.QuestionText, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.QuestionText, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QuestionAnswer, htmlAttributes: new { @class = "control-label" })
        @Html.TextBoxFor(model => model.QuestionAnswer, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.QuestionAnswer, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a href="@Url.Action("Index", "Question")" class="btn btn-secondary">Back to List</a>
    </div>
}